In [1]:
import numpy as np
arr=np.array([20,34,54,76,11])
arr

array([20, 34, 54, 76, 11])

In [2]:
arr.shape

(5,)

In [3]:
arr.size

5

In [4]:
arr[2]

np.int64(54)

In [5]:
arr[len(arr)-1]

np.int64(11)

In [6]:
arr[1:4]

array([34, 54, 76])

In [7]:
a=np.array([1,2,3])
b=np.array([11,22,33])

In [8]:
a+b

array([12, 24, 36])

In [9]:
a*b

array([11, 44, 99])

In [10]:
a-b

array([-10, -20, -30])

In [11]:
#r=[]
#for i in range(9):
#    x=int(input())
#   r.append(x)

#r=np.array([r])

In [21]:
lr=np.linspace(1,10,5)
lr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
rr=np.arange(9)
rr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
rr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
rnd=np.random.rand(5)

In [41]:
r1=[]

for i in range(5):
    num=np.random.randint(1,50)
    r1.append(num)
r2=np.array(r1)
r2

array([24, 19, 36, 18, 48])

In [45]:
st=np.array([12, 45, 23, 67, 34])
print(np.min(st))
print(np.max(st))
print(np.mean(st))
print(np.median(st))
print(np.sum(st))

12
67
36.2
34.0
181


In [46]:
rr+10

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [56]:
ax=np.array([[1,2,3],[4,5,6],[7,8,9]])
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
print(ax[1])

for i in ax:
    print(i[2])
    
sum=0
for i in ax:
    for j in i:
        sum+=j
print(sum)

print(ax.sum(axis=0))
print(ax.sum(axis=1))

[4 5 6]
3
6
9
45
[12 15 18]
[ 6 15 24]


In [72]:
p1=np.arange(1,20+1)
for i in range(20):
    if p1[i]%2!=0:
        print(p1[i])

1
3
5
7
9
11
13
15
17
19


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
p2=np.arange(1,13)
rp2=p2.reshape(3,4)
rp2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
np.argmax(rp2) #print index of maximum num

np.int64(11)

In [77]:
r2

array([24, 19, 36, 18, 48])

In [80]:
r2[2]=90
r2

array([24, 19, 90, 18, 48])

In [82]:
r2[np.where(r2>25)]

array([90, 48])

In [83]:
r2/2

array([12. ,  9.5, 45. ,  9. , 24. ])