# NumPy Basics

In [1]:
import numpy as np

# Ways to create arrays

In [2]:
arr=np.array([12,14,16], np.int32)

In [3]:
arr2=np.array([[2,1,6,8], [23,45,67,30]])

In [4]:
print(arr.shape)
print(arr2.shape)

(3,)
(2, 4)


In [5]:
arr.dtype

dtype('int32')

In [6]:
arr.size

3

In [7]:
arr=np.array((12,14,16), np.int32)
arr

array([12, 14, 16], dtype=int32)

In [8]:
np.mean(arr)

np.float64(14.0)

In [9]:
np.median(arr)

np.float64(14.0)

In [56]:
z=np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [57]:
np.random.rand(2)

array([0.06045053, 0.22028372])

In [11]:
rg=np.arange(10)
rg

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
linearspace=np.linspace(1,10,5)
linearspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
emp=np.empty((2,4))   #random array values we can change it
emp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
emp2=np.empty_like(rg)   #copy another array values so we can change it
emp2

array([-1,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [15]:
identity=np.identity(10) #identity array
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
ar2=np.arange(9)
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
rarr=ar2.reshape(3,3)
rarr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
ravel_rarr=rarr.ravel()
ravel_rarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

# Axis

In [19]:
ar11=np.array([[91,92,93],[81,82,83]])
ar11

array([[91, 92, 93],
       [81, 82, 83]])

In [20]:
print(ar11.sum(axis=0))
print(ar11.sum(axis=1))

[172 174 176]
[276 246]


In [21]:
ar11.ndim

2

In [22]:
ar11.size

6

In [23]:
ar11.nbytes

48

In [24]:
ar11.T    #TRANSPOSE OF ARRAY

array([[91, 81],
       [92, 82],
       [93, 83]])

In [25]:
ar11

array([[91, 92, 93],
       [81, 82, 83]])

In [26]:
farr=ar11.flat

for items in farr:
    print(items)

91
92
93
81
82
83


In [27]:
ar12=np.array([23,34,5,54])

In [28]:
ar12.argmax()     #to get maximum number index from array

np.int64(3)

In [29]:
ar12.argmin()     #to get minimum number index from array

np.int64(2)

In [30]:
ar11.argmin(axis=0)   

array([1, 1, 1])

In [31]:
ar12.argsort()

array([2, 0, 1, 3])

In [32]:
ar11.argsort()

array([[0, 1, 2],
       [0, 1, 2]])

In [33]:
m1=np.array([[1,1],[2,2]])
m1

array([[1, 1],
       [2, 2]])

In [34]:
m2=np.array([[5,7],[12,8]])
m2

array([[ 5,  7],
       [12,  8]])

In [35]:
m1+m2

array([[ 6,  8],
       [14, 10]])

In [36]:
m1*m2

array([[ 5,  7],
       [24, 16]])

In [50]:
m2+5

array([[10, 12],
       [17, 13]])

In [37]:
np.sqrt(m2)

array([[2.23606798, 2.64575131],
       [3.46410162, 2.82842712]])

In [38]:
np.sum(m2)

np.int64(32)

In [39]:
np.min(m2)

np.int64(5)

In [40]:
np.max(m2)

np.int64(12)

In [41]:
m2

array([[ 5,  7],
       [12,  8]])

In [42]:
print(np.where(m2>5))

type(np.where(m2>5))

(array([0, 1, 1]), array([1, 0, 1]))


tuple

In [43]:
np.nonzero(m2)

(array([0, 0, 1, 1]), array([0, 1, 0, 1]))

In [44]:
np.count_nonzero(m2)

4

In [45]:
import sys

In [46]:
sys.getsizeof(1)*len(m2)

56

In [47]:
m2.itemsize*m2.size

32

In [48]:
m2.tolist()

[[5, 7], [12, 8]]